name: Exécuter le lab3

on:
  push:
    branches:
      - main

jobs:
  run_lab3:
    runs-on: ubuntu-latest

    steps:
    - name: Vérification du dépôt
      uses: actions/checkout@v2 # Cette action permet de récupérer le code du dépôt

    - name: Exécuter le lab3
      run: |
        cd lab3
        # Insérez ici les commandes que vous souhaitez exécuter dans le dossier "lab3"